// <auto-generated />
using System;
using Business.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Business.Infrastructure.Migrations.Product
{
  [DbContext(typeof(AppDbContext))]
  [Migration("20250919183737_InitialMigration")]
  partial class InitialMigration
  {
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "9.0.8")
          .HasAnnotation("Relational:MaxIdentifierLength", 128);

      SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

      modelBuilder.Entity("Business.Core.Models.Entities.ApplicationUser", b =>
          {
            b.Property<int>("UserId")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

            b.Property<int>("CreatedBy")
                      .HasColumnType("int");

            b.Property<DateTime>("CreatedOn")
                      .HasColumnType("datetime2");

            b.Property<string>("Email")
                      .IsRequired()
                      .HasMaxLength(256)
                      .HasColumnType("nvarchar(256)");

            b.Property<string>("FirstName")
                      .IsRequired()
                      .HasMaxLength(64)
                      .HasColumnType("nvarchar(64)");

            b.Property<string>("Surname")
                      .IsRequired()
                      .HasMaxLength(64)
                      .HasColumnType("nvarchar(64)");

            b.Property<int>("UpdatedBy")
                      .HasColumnType("int");

            b.Property<DateTime>("UpdatedOn")
                      .HasColumnType("datetime2");

            b.Property<string>("UserName")
                      .IsRequired()
                      .HasMaxLength(32)
                      .HasColumnType("nvarchar(32)");

            b.HasKey("UserId");

            b.ToTable("ApplicationUsers");

            b.HasData(
                      new
                      {
                        UserId = 1,
                        CreatedBy = 1,
                        CreatedOn = new DateTime(2025, 9, 19, 18, 37, 36, 728, DateTimeKind.Utc).AddTicks(1689),
                        Email = "SYSTEM@Application.com",
                        FirstName = "SYSTEM",
                        Surname = "SYSTEM",
                        UpdatedBy = 1,
                        UpdatedOn = new DateTime(2025, 9, 19, 18, 37, 36, 728, DateTimeKind.Utc).AddTicks(1909),
                        UserName = "SYSTEM"
                      });
          });
#pragma warning restore 612, 618
    }
  }
}